name: ToolFuzz
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fqdn=1.5.1
  - frozenlist=1.4.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - multidict=6.0.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - openssl=3.0.14
  - overrides=7.7.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.3
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - aioboto3==14.0.0
      - aiobotocore==2.20.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aioitertools==0.12.0
      - alembic==1.14.1
      - antlr4-python3-runtime==4.13.1
      - appdirs==1.4.4
      - arxiv==2.1.3
      - asgiref==3.8.1
      - astor==0.8.1
      - asyncer==0.0.8
      - asyncio-atexit==1.0.1
      - atheris==2.3.0
      - atheris-libprotobuf-mutator==0.1.2
      - auth0-python==4.8.0
      - autogen-agentchat==0.4.8
      - autogen-core==0.4.8
      - autogen-ext==0.4.8
      - autogenstudio==0.4.1.1
      - azure-ai-documentintelligence==1.0.0
      - azure-ai-inference==1.0.0b8
      - azure-core==1.32.0
      - azure-identity==1.20.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - blinker==1.9.0
      - boto3==1.36.23
      - botocore==1.36.23
      - bs4==0.0.2
      - build==1.2.2.post1
      - cachetools==5.3.3
      - cargo==0.3
      - cattrs==23.2.3
      - certifi==2025.1.31
      - chardet==5.2.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.23
      - click==8.1.8
      - click-log==0.4.0
      - cobble==0.1.4
      - cohere==5.13.12
      - coloredlogs==15.0.1
      - composio-autogen==0.7.5
      - composio-core==0.7.5
      - composio-crewai==0.7.5
      - composio-langchain==0.7.5
      - composio-llamaindex==0.7.5
      - composio-openai==0.7.2
      - contourpy==1.2.1
      - coverage==7.5.4
      - crewai==0.102.0
      - crewai-tools==0.36.0
      - crosshair-tool==0.0.61
      - cryptography==44.0.1
      - cssselect==1.2.0
      - cssselect2==0.7.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.0.1
      - datrie==0.8.2
      - deep-ast==0.0.1
      - deeplake==3.9.42
      - deprecated==1.2.14
      - deprecation==2.1.0
      - diff-match-patch==20230430
      - dill==0.3.8
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - dnspython==2.7.0
      - docker==7.1.0
      - docstring-parser==0.16
      - duckduckgo-search==6.2.2
      - durationpy==0.9
      - easyplotly==0.1.3
      - email-validator==2.2.0
      - embedchain==0.1.126
      - enforce==0.3.4
      - et-xmlfile==2.0.0
      - fake-useragent==2.0.3
      - faker==26.0.0
      - fast-depends==2.4.12
      - fastapi==0.115.8
      - fastapi-cli==0.0.7
      - fastavro==1.10.0
      - feedparser==6.0.11
      - fibheap==0.2.1
      - filelock==3.16.1
      - filetype==1.2.0
      - flaml==2.2.0
      - flatbuffers==25.2.10
      - fonttools==4.53.1
      - frozendict==2.4.4
      - fsspec==2024.6.1
      - fuzzingbook==0.8.0
      - gitdb==4.0.11
      - github-dependents-info==1.6.3
      - gitpython==3.1.43
      - google-api-core==2.19.1
      - google-api-python-client==2.151.0
      - google-auth==2.31.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-aiplatform==1.80.0
      - google-cloud-bigquery==3.25.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.63.2
      - gptcache==0.1.44
      - gql==3.5.0
      - grammar-graph==0.2.0
      - grammar-to-regex==1.0.1
      - graphql-core==3.2.3
      - greenlet==3.1.1
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.70.0
      - grpcio-status==1.64.1
      - grpcio-tools==1.70.0
      - html2text==2024.2.26
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - huggingface-hub==0.29.1
      - humanfriendly==10.0
      - humbug==0.3.2
      - ijson==3.3.0
      - inflection==0.5.1
      - iniconfig==2.0.0
      - instructor==1.7.2
      - ionic-api-sdk==0.7.1
      - ionic-langchain==0.2.3
      - ipython-genutils==0.2.0
      - isla-solver==1.14.4
      - isodate==0.7.2
      - jinja2==3.1.5
      - jiter==0.7.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json-repair==0.39.0
      - json-schema-to-pydantic==0.2.2
      - json5==0.10.0
      - jsonpath-python==1.0.6
      - jsonpickle==4.0.2
      - jsonref==1.1.0
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.4
      - kiwisolver==1.4.5
      - kubernetes==32.0.1
      - lancedb==0.19.0
      - langchain==0.3.7
      - langchain-cohere==0.3.5
      - langchain-community==0.3.5
      - langchain-core==0.3.36
      - langchain-experimental==0.3.3
      - langchain-google-community==2.0.2
      - langchain-openai==0.2.5
      - langchain-text-splitters==0.3.2
      - langchainhub==0.1.20
      - langgraph==0.2.45
      - langgraph-checkpoint==2.0.2
      - langgraph-sdk==0.1.35
      - langsmith==0.1.139
      - libdeeplake==0.0.158
      - lightning-utilities==0.11.7
      - litellm==1.60.2
      - lizard==1.17.10
      - llama-cloud==0.1.12
      - llama-cloud-services==0.6.1
      - llama-index==0.12.17
      - llama-index-agent-coa==0.3.0
      - llama-index-agent-openai==0.4.5
      - llama-index-cli==0.4.0
      - llama-index-core==0.12.17
      - llama-index-embeddings-openai==0.3.1
      - llama-index-indices-managed-llama-cloud==0.6.4
      - llama-index-llms-openai==0.3.19
      - llama-index-multi-modal-llms-openai==0.4.3
      - llama-index-packs-agents-lats==0.3.0
      - llama-index-program-openai==0.3.1
      - llama-index-question-gen-openai==0.3.0
      - llama-index-readers-file==0.4.5
      - llama-index-readers-llama-parse==0.4.0
      - llama-index-tools-arxiv==0.3.0
      - llama-index-tools-duckduckgo==0.3.0
      - llama-index-tools-jina==0.0.1
      - llama-index-tools-weather==0.3.0
      - llama-index-tools-wikipedia==0.3.0
      - llama-index-tools-yahoo-finance==0.3.0
      - llama-parse==0.6.1
      - loguru==0.7.3
      - lsprotocol==2023.0.1
      - lxml==5.2.2
      - lz4==4.4.3
      - mako==1.3.9
      - mammoth==1.9.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markdownify==0.14.1
      - markitdown==0.0.1a4
      - marshmallow==3.21.3
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - mediawikiapi==1.2
      - mem0ai==0.1.50
      - mmh3==5.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - msal==1.31.1
      - msal-extensions==1.2.0
      - msgpack==1.1.0
      - multiprocess==0.70.16
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - networkx==3.3
      - nltk==3.9.1
      - nodeenv==1.9.1
      - notedown==1.5.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - olefile==0.47
      - onnxruntime==1.20.1
      - openai==1.63.0
      - openpyxl==3.1.5
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-grpc==1.30.0
      - opentelemetry-exporter-otlp-proto-http==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - orjson==3.10.11
      - outcome==1.3.0.post0
      - pandas==2.2.2
      - pandoc-attributes==0.1.7
      - parameterized==0.9.0
      - paramiko==3.5.1
      - parse==1.20.2
      - pathos==0.3.2
      - pathvalidate==3.2.3
      - pdfminer-six==20231228
      - pdfplumber==0.11.5
      - peewee==3.17.9
      - pillow==11.1.0
      - playwright==1.50.0
      - plotly==5.22.0
      - pluggy==1.5.0
      - portalocker==2.10.1
      - posthog==3.14.1
      - pox==0.3.4
      - ppft==1.7.6.8
      - propcache==0.2.1
      - proto-plus==1.24.0
      - protobuf==5.29.3
      - proxyorderedset==0.3.5
      - psycopg==3.2.4
      - puremagic==1.28
      - pyan==1.0.4.dev1+g7fa04c8
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyautogen==0.7.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.6.1
      - pydantic-yaml==1.3.0
      - pydot==1.4.2
      - pydriller==2.6
      - pydub==0.25.1
      - pyee==11.1.1
      - pygithub==2.3.0
      - pygls==1.3.1
      - pygraphviz==1.13
      - pyjwt==2.9.0
      - pylance==0.23.0
      - pynacl==1.5.0
      - pyparsing==2.4.7
      - pypdf==5.3.0
      - pypdfium2==4.30.1
      - pyperclip==1.9.0
      - pypika==0.48.9
      - pyppeteer==2.0.0
      - pyproject-hooks==1.2.0
      - pyquery==2.0.1
      - pyreqwest-impersonate==0.5.3
      - pyright==1.1.394
      - pysbd==0.3.4
      - pysher==1.0.8
      - pytest==7.4.4
      - python-dotenv==1.0.1
      - python-graphviz==0.20.3
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytube==15.0.0
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - qdrant-client==1.13.2
      - regex==2024.11.6
      - reportlab==4.2.2
      - requests-html==0.10.0
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - returns==0.23.0
      - rich==13.7.1
      - rich-toolkit==0.13.2
      - rsa==4.9
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.11.2
      - safetensors==0.5.2
      - schema==0.7.7
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - selenium==4.22.0
      - semanticscholar==0.8.4
      - semver==3.0.4
      - sentence-transformers==3.4.1
      - sentry-sdk==2.22.0
      - sgmllib3k==1.0.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - showast==0.2.4
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - speechrecognition==3.14.1
      - sqlalchemy==2.0.35
      - sqlmodel==0.0.22
      - stackapi==0.3.1
      - starlette==0.45.3
      - striprtf==0.0.26
      - svglib==1.5.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.20.3
      - toml==0.10.2
      - tomli==2.2.1
      - tomli-w==1.2.0
      - torch==2.4.1
      - torchmetrics==1.4.2
      - transformers==4.49.0
      - tree-sitter==0.24.0
      - tree-sitter-python==0.23.6
      - trio==0.26.0
      - trio-websocket==0.11.1
      - triton==3.0.0
      - typer==0.15.1
      - types-pytz==2024.1.0.20240417
      - types-requests==2.32.0.20240622
      - typeshed-client==2.7.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uv==0.6.1
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - w3lib==2.3.1
      - watchfiles==1.0.4
      - websockets==14.2
      - wikibase-rest-api-client==0.1.4
      - wikipedia==1.4.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xlrd==2.0.1
      - xlsxwriter==3.2.2
      - xmltodict==0.13.0
      - xxhash==3.5.0
      - yapf==0.40.2
      - yarl==1.18.3
      - yfinance==0.2.53
      - youtube-search==2.1.2
      - youtube-transcript-api==0.6.3
      - z3-solver==4.13.0.0